[package]
name = "opensea-v2"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
ethers = { version = "2", features = ["ws", "rustls"] }
reqwest = { version = "0.11.14", default-features = false, features = [
    "rustls-tls",
] }
serde = "1.0.152"
thiserror = "1.0.40"
serde_json = { version = "1.0", features = [
    "arbitrary_precision",
    "preserve_order",
] }
serde_with = { version = "3.1.0", features = ["chrono_0_4"] }
serde_repr = "0.1.16"
chrono = { version = "0.4.26", features = ["serde"] }
strum = { version = "0.25.0", features = ["derive"] }

[dev-dependencies]
tokio = { version = "1.32.0", features = ["macros"] }
